from lecture_processor.runtime import core

save_purchase_record = core.save_purchase_record
purchase_record_exists_for_session = core.purchase_record_exists_for_session
process_checkout_session_credits = core.process_checkout_session_credits
