export const minifiedTargets = [
  { entry: 'static/js/dashboard.js', out: 'static/js/dashboard.min.js' },
  { entry: 'static/js/batch-dashboard.js', out: 'static/js/batch-dashboard.min.js' },
  { entry: 'static/js/batch-mode.js', out: 'static/js/batch-mode.min.js' },
  { entry: 'static/js/buy-credits.js', out: 'static/js/buy-credits.min.js' },
  { entry: 'static/js/index-app.js', out: 'static/js/index-app.min.js' },
  { entry: 'static/js/index-results-utils.js', out: 'static/js/index-results-utils.min.js' },
  { entry: 'static/js/admin.js', out: 'static/js/admin.min.js' },
  { entry: 'static/js/physio.js', out: 'static/js/physio.min.js' },
  { entry: 'static/js/reader.js', out: 'static/js/reader.min.js' },
  { entry: 'static/js/shared-study.js', out: 'static/js/shared-study.min.js' },
  { entry: 'static/js/study-api-utils.js', out: 'static/js/study-api-utils.min.js' },
  { entry: 'static/js/study.js', out: 'static/js/study.min.js' },
  { entry: 'static/js/voice-notes-utils.js', out: 'static/js/voice-notes-utils.min.js' },
  { entry: 'static/js/voice-notes.js', out: 'static/js/voice-notes.min.js' },
];

export const intentionallyUnminifiedScripts = [
  'static/js/app-shell.js',
  'static/js/auth-utils.js',
  'static/js/calendar.js',
  'static/js/display-format-utils.js',
  'static/js/download-utils.js',
  'static/js/features.js',
  'static/js/firebase-bootstrap.js',
  'static/js/general-transcriber.js',
  'static/js/html-utils.js',
  'static/js/index-analytics-utils.js',
  'static/js/index-processing-ui.js',
  'static/js/index-progress-utils.js',
  'static/js/lecture-audio-import-utils.js',
  'static/js/lecture-downloader.js',
  'static/js/markdown-utils.js',
  'static/js/plan.js',
  'static/js/runtime-job-utils.js',
  'static/js/study-library-utils.js',
  'static/js/study-progress-utils.js',
  'static/js/study-session-utils.js',
  'static/js/topbar-utils.js',
  'static/js/ui-cache.js',
  'static/js/user-cache-utils.js',
  'static/js/ux-utils.js',
  'static/js/video-overlay-builder-utils.js',
  'static/js/video-overlay-builder.js',
];
